name: Weight-RPG
version: '${project.version}'
main: ted_2001.WeightRPG.WeightRPG
api-version: 1.13
author: Ted_2001
softdepend: [WorldGuard, PlaceholderAPI]
description: Inventory weight mechanic just like in RPGs.
commands:
  weight:
    description: Shows the weight of the player.
    permission: weight.use
    usage: /weight
  weight get:
    description: Shows the weight of the player.
    permission: weight.get
    usage: /weight get <item>
  weight set:
    description: Sets the weight of the player.
    permission: weight.set
    usage: /weight set <item> <weight>
  weight add:
    description: Adds the item to the weight files.
    permission: weight.add
    usage: /weight add <item> <weight>
  weight help:
    description: Shows the help message.
    permission: weight.help
    usage: /weight help
  weight reload:
    description: Reloads the plugin.
    permission: weight.reload
    usage: /weight reload