name: Weight-RPG
version: '${project.version}'
main: ted_2001.WeightRPG.WeightRPG
api-version: 1.18
authors: [ Ted_2001 ]
commands:
  weight:
    description: List of all commands for Weight RPG Plugin.
    permission: weight.use


