name: Weight-RPG
version: '${project.version}'
main: ted_2001.WeightRPG.WeightRPG
api-version: 1.13
author: Ted_2001
softdepend: [WorldGuard, PlaceholderAPI]
description: Inventory weight mechanic just like in RPGs.
commands:
  weight:
    description: Shows the weight of the player.
    permission: weight.use
  weight-get:
    description: Shows the weight of the item.
    permission: weight.use
  weight-set:
    description: Sets the weight of the item.
    permission: weight.use
  weight-add:
    description: Adds an item to the weight files.
    permission: weight.use
  weight-reload:
    description: Reloads all files and applies changes to the server.
    permission: weight.use