name: Weight-RPG
version: '${project.version}'
main: ted_2001.WeightRPG.WeightRPG
api-version: 1.13
authors: [ Ted_2001 ]
softdepend: [WorldGuard]
commands:
  weight:
    description: Shows the weight of the player.
    permission: weight.use



