name: Weight-RPG
version: '${project.version}'
main: ted_2001.WeightRPG.WeightRPG
api-version: 1.13
author: Ted_2001
softdepend: [WorldGuard, PlaceholderAPI]
description: Inventory weight mechanic just like in RPGs.
commands:
  weight:
    description: Shows the weight of the player.
    permission: weight.use
    usage: /weight
